language: php

php:
  - 7.1

before_script:
  - echo "xdebug.overload_var_dump = 0" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - composer install

script:
  - php tests/units/runner.php
